### ISSUE TITLE
Steps to start sriov controller in packet.net env

### ISSUE THREAD

**Issue by sbezverk** [ligato/networkservicemesh#276]
Tested on Centos 7.5 with 2  Mellanox SRIOV capable adpters.
01:00.0 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx]
01:00.1 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx]

1. Enable SRIOV support in BIOS (I used server serial console connection to change server's bios settings).
2. Update OS (optional)
3. Add grub2' boot command line `amd_iommu=on iommu=pt` if server platform is Intel and not AMD as in my case, change `amd_iommu` for `intel_iommu`
4. Remove one of bundle member from the bundle. (I edited `/etc/sysconfig/network-scripts/ifcfg-enp1s0f1`)
```
DEVICE=enp1s0f1
ONBOOT=yes
HWADDR=ec:0d:9a:c0:05:39
BOOTPROTO=none
```
5. Enable VFs for the link which was removed from the bundle:
```
num_vf_enabled=8
dev=enp1s0f1
echo $num_vf_enabled > /sys/class/net/$dev/device/sriov_numvfs
```
6. Install kubernetes, follow this steps:

https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

7. Clone networkservicemesh repo and build `nsm-generate-sriov-configmap`

cd cmd/nsm-generate-sriov-configmap
go build

8. run `nsm-generate-sriov-configmap` to discover all VFs available on the local host, bind them to vfio driver and to generate configmap.
```
./nsm-generate-sriov-configmap --kubeconfig /root/.kube/config
``` 
where --kubeconfig points to kubeconfig file generated during installation on the cluster
the configmap name follows this format: `nsm-sriov-configmap-{hostname}.yaml` 

9. Edit configmap's `networkService: networkservicemesh.io/sriov-{name of network service}` to assign VF to corresponding network services. Please keep ``sriov-`` prefix for network services. Do not change any other fields.

```
apiVersion: v1
data:
  0000-01-01.2: |
    networkService: networkservicemesh.io/sriov-vlan10
    parentDevice: enp1s0f1
    pciAddr: "0000:01:01.2"
    vfLocalID: 0
    vfioDevice: /dev/vfio/65
  0000-01-01.3: |
    networkService: networkservicemesh.io/sriov-vlan10
    parentDevice: enp1s0f1
    pciAddr: "0000:01:01.3"
    vfLocalID: 1
    vfioDevice: /dev/vfio/66
  0000-01-01.4: |
    networkService: networkservicemesh.io/sriov-trunk
    parentDevice: enp1s0f1
    pciAddr: "0000:01:01.4"
    vfLocalID: 2
    vfioDevice: /dev/vfio/67
  0000-01-01.5: |
    networkService: networkservicemesh.io/sriov-trunk
    parentDevice: enp1s0f1
    pciAddr: "0000:01:01.5"
    vfLocalID: 3
    vfioDevice: /dev/vfio/68
  0000-01-01.6: |
    networkService: networkservicemesh.io/sriov-trunk
    parentDevice: enp1s0f1
    pciAddr: "0000:01:01.6"
    vfLocalID: 4
    vfioDevice: /dev/vfio/69
  0000-01-01.7: |
    networkService: networkservicemesh.io/sriov-trunk
    parentDevice: enp1s0f1
    pciAddr: "0000:01:01.7"
    vfLocalID: 5
    vfioDevice: /dev/vfio/70
  0000-01-02.0: |
    networkService: networkservicemesh.io/sriov-vlan20
    parentDevice: enp1s0f1
    pciAddr: "0000:01:02.0"
    vfLocalID: 6
    vfioDevice: /dev/vfio/71
  0000-01-02.1: |
    networkService: networkservicemesh.io/sriov-vlan20
    parentDevice: enp1s0f1
    pciAddr: "0000:01:02.1"
    vfLocalID: 7
    vfioDevice: /dev/vfio/72
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    networkservicemesh.io/sriov: config
    networkservicemesh.io/sriov-node-name: sbezverk-srv-01
  name: nsm-sriov-vf-list
  namespace: default
```
10.  Instantiate configmap object by running:
```
kubectl create -f nsm-sriov-configmap-{your hostname}.yaml
```
11.  Start sriov controller. networkservicemesh repo comes with sriov-controller.yaml file which can be used to start the controller:
```
kubectl create -f controllers/sriov-controller/sriov-controller.yaml
```
you should see controller running:
```
kubectl get pods | grep sriov-controller

sriov-controller-5s6v6      1/1       Running   0          1h

```

You should also see Capacity section and Allocatable section listing your network services in the output of `kubectl describe node {your hostname}`

```console
kubectl describe node sbezverk-srv-01
Name:               sbezverk-srv-01

Addresses:
  InternalIP:  10.99.211.129
  Hostname:    sbezverk-srv-01
Capacity:                                 < -------------------------- See sriov prefixed
 cpu:                                 48
 ephemeral-storage:                   112766084Ki
 hugepages-1Gi:                       4Gi
 hugepages-2Mi:                       0
 memory:                              65631208Ki
 networkservicemesh.io/sriov-trunk:   4
 networkservicemesh.io/sriov-vlan10:  2
 networkservicemesh.io/sriov-vlan20:  2
 pods:                                110
Allocatable:                              < -------------------------- See sriov prefixed
 cpu:                                 48
 ephemeral-storage:                   103925222843
 hugepages-1Gi:                       4Gi
 hugepages-2Mi:                       0
 memory:                              61334504Ki
 networkservicemesh.io/sriov-trunk:   4
 networkservicemesh.io/sriov-vlan10:  2
 networkservicemesh.io/sriov-vlan20:  2
 pods:                                110

```
12.  Client pod example is not executable, but for demonstation purposes only to give example how to request VF's provided network services.

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nsm-sriov-client
    spec:
      containers:
        - image: docker.io/alpine:3.8
          name: nsm-sriov-client
          command:
            - /bin/sh
            - -xec
            - |
              while true; do ( echo "Doing nothing"; sleep 30; ) done
          imagePullPolicy: Always
          resources:
            limits:
#
# Specify the list of network services required for a client pod.
# The format should be: networkservicemesh.io/sriov-{network service name}: {number of services}
#
#              networkservicemesh.io/sriov-trunk: 2
#              networkservicemesh.io/sriov-vlan10: 1
#              networkservicemesh.io/sriov-vlan20: 1
#              networkservicemesh.io/sriov-mgmt: 1
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
metadata:
  name: nsm-sriov-client
  namespace: default
```

13. Once your client successfully received requested resources,  you should see them in `Allocated resources` section of  `kubectl describe node {your hostname}`

```console
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                            Requests    Limits
  --------                            --------    ------
  cpu                                 1 (2%)      0 (0%)
  memory                              140Mi (0%)  340Mi (0%)
  networkservicemesh.io/sriov-trunk   2           2
  networkservicemesh.io/sriov-vlan10  1           1
  networkservicemesh.io/sriov-vlan20  1           1
```
